import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const here=dirname(fileURLToPath(import.meta.url));
const dist=resolve(process.argv[2]||'dist');
const label=process.argv[3]||'after';
const manifest=JSON.parse(readFileSync(resolve(dist,'.vite/manifest.json'),'utf8'));
const deferredDynamicImports=Object.entries(manifest).filter(([,entry])=>entry.isDynamicEntry).map(([key])=>({key,trigger:'interaction',reason:key.includes('success')?'Shown only after successful user export':key.includes('prompt-bundle')?'Prompt view or explicit selected-prompt export':'Case card hover/focus intent or opening detail'}));
const urls=['/','/prompts','/prompts/collections','/prompts/collections/gpt6','/prompts/collections/gpt-6-astra','/showcases','/showcases/collections','/showcases/collections/gpt6','/showcases/collections/gpt-6-astra'];
const config={base:'/',routes:urls.map(url=>({url,html:'index.html',entry:'index.html',kind:'public',initialDynamicImports:[],deferredDynamicImports,initialFonts:['_prompts/fonts/poppins-400-v1.woff2','_prompts/fonts/poppins-500-v1.woff2','_prompts/fonts/poppins-600-v1.woff2','_prompts/fonts/space-grotesk-v1.woff2','_prompts/fonts/dm-sans-v1.woff2','_prompts/fonts/jetbrains-mono-v1.woff2',...(!url.includes('/collections')?['_prompts/media/curved-gallery/inter-regular.woff2']:[])],...(url.endsWith('collections')?{}:{lcpImage:'/_prompts/images/showcase/prism-1280-v1.webp'})}))};
const configPath=resolve(here,`audit-${label}.config.json`);
writeFileSync(configPath,JSON.stringify(config,null,2));
const result=spawnSync(process.execPath,[resolve(here,'audit-vite-build.mjs'),'--profile','marketing','--dist',dist,'--config',configPath,'--strict'],{encoding:'utf8'});
writeFileSync(resolve(here,`build-${label}.json`),result.stdout);
if(result.stderr)console.error(result.stderr);
const report=JSON.parse(result.stdout);
console.log(JSON.stringify({exit:result.status,errors:report.errors,warnings:[...new Set(report.warnings.map(w=>w.code+': '+w.message))]},null,2));
process.exitCode=result.status;
